### ISSUE TITLE
Using bower install installs other directive

### ISSUE THREAD

**Issue by Jacq** [Goldark/angular-file-input#1]
Using _bower install angular-file-input_ installs directive https://github.com/twhitbeck/angular-file-input instead of this one.
Bower search Goldark doest not list this directive only
ng-json-explorer git://github.com/Goldark/ng-json-explorer.git
goldark-angularjs-sdk git://github.com/Goldark/angularjs-sdk.git

**Comment by odra** [comment]
I changed the bower  package name to "simple-angular-file-input", so now you can run "bower install simple-angular-file-input" to install the module.
